### PR TITLE
Update URLs to `selectmenu` proposal

### PR DESCRIPTION
**Pull request by djeglin**
This PR updates the URLs in both the readme and index.html that point to the `selectmenu` proposal.

### CODE REVIEW

**Comment by djeglin** [comment]
@microsoft-github-policy-service agree

--
David Eglin

**Comment by YoungAmabelAlceraDelamerced** [comment]
Dear gentlemen,

I am under unawareness of ownership stated in your forwarded letter. We All
know that I am the real Owner of the things that you've trying to disclosed
to me. This Systems was related to my Life Cycle, My personal Life.Its
impossible to believed to proof in your side that its belongs to youm Don't
say the statement my contribution, everything was coming from me the reason
you are all trying to link in all my devices as I am the root if these
products, I can't able to allow you manage my own business as it is my own
personal life cycle. Better to say to give to the right Owner which is me
then let's make something towards your own productions which is case to
case basis amount to give to you based on what you really produced and that
is not copied from what I being developef. We can able to give every things
on way of conforming me based on the production you've made and closed to
gave sort of information on how you feral with Government payments as it is
all I've produced on all things you submitted to them yet to be involved me
or include me being the Director of these products that seems you tried to
make it your  Company. it is part if all my products that I produced and my
plan to make it a Corp that is affiliated with my existing Corporation. Be
as it will be made to give your own business or make it in proper way time
resolved this annoying ownership. As I have said it is related to my own
personal life cycle. Means cannot be awarded to anyone who just grab from
my devices then suddenly became the owner of my own invented buss. System.

Pls. Give proper assumption on where you have to place yourself iny own
created buss.system,

Pls remind that this may soon submit to right department as it was already
affect the eco-progress.

Amabel dela Merced

Real Owner of my own products Microsoft and Gift-Hub

**Comment by YoungAmabelAlceraDelamerced** [comment]
By the way ,jut to ket you know tgar I am "Al"

Regards
Amabel "Al"cera dela Merxed

**Review by captainbrosset — APPROVED** [review]
Thanks a lot for providing this PR.

**Pull request merged**
